# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

stages:
  - lint
  - build
  - test
  - coverage
  - release
  - deploy


variables:
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

  RELEASE_REGISTRY: docker.io
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-amqp-trigger-organisation-gatekeeper

  PYTEST_COV_MODULE: orggatekeeper
  PYTEST_COV_FAIL_UNDER: 100

  PRECOMMIT_USE_POETRY: "true"
  POETRY_VERSION: "1.4.1"

  PRODUCT: os2mo
  COMPONENT: orggatekeeper



# Conditions
#############
.if-default-branch-refs: &if-default-branch-refs
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-tag: &if-tag
  if: '$CI_COMMIT_TAG'

.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'

# Workflow
###########
workflow:
  rules:
    - <<: *if-tag
    - <<: *if-default-branch-refs
    - <<: *if-merge-request


include:
  - project: labs/salt-automation
    file:
    - gitlab-ci-templates/common/conventional-commits.v1.yml
    - gitlab-ci-templates/python/pytest.v1.yml
    - gitlab-ci-templates/common/docker-release.v1.yml
    - gitlab-ci-templates/common/docker-build-meta.v2.yml
    - gitlab-ci-templates/common/pre-commit.v1.yml
    - gitlab-ci-templates/common/config-updater-flux.v1.yml
    - gitlab-ci-templates/common/config-updater-salt.v1.yml

# Build
########
Build:
  extends: .build-docker
  variables:
    BUILD_DOCKER_EXTRA_FLAGS: "--build-arg=COMMIT_SHA=${CI_COMMIT_SHA} --build-arg=COMMIT_TAG=${CI_COMMIT_TAG}"
