facets:
  org_unit_hierarchy:
    linjeorg:
      title: "Linjeorganisation"
      scope: "TEXT"
    selvejet:
      title: "Selvejet institution"
      scope: "TEXT"
    hide:
      title: "Skjult organisation"
      scope: "TEXT"
    NA:
      title: "Udenfor organisation"
      scope: "TEXT"
it_systems:
  SD_uuid: "SD UUID"
