# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

query GetOrgUnitHierarchy($filter: OrganisationUnitFilter!) {
  org_units(filter: $filter) {
    objects {
      validities {
        unit_hierarchy_response {
          validities {
            uuid
          }
        }
      }
    }
  }
}

query GetOrgUnitDetails($filter: OrganisationUnitFilter!) {
  org_units(filter: $filter) {
    objects {
      validities {
        name
        user_key
        unit_hierarchy_response {
          uuid
        }
        unit_type_response {
          uuid
        }
        unit_level_response {
          uuid
        }
        parent_response {
          uuid
        }
        validity {
          from
          to
        }
      }
    }
  }
}

query GetClassByUserKey($filter: ClassFilter!) {
  classes(filter: $filter) {
    objects {
      uuid
      current {
        user_key
      }
    }
  }
}

mutation CreateOrgUnit($input: OrganisationUnitCreateInput!) {
  org_unit_create(input: $input) {
    uuid
  }
}

mutation CreateFacet($input: FacetCreateInput!) {
  facet_create(input: $input) {
    uuid
  }
}

mutation CreateClass($input: ClassCreateInput!) {
  class_create(input: $input) {
    uuid
  }
}

mutation CreateEmployee($input: EmployeeCreateInput!) {
  employee_create(input: $input) {
    uuid
  }
}

mutation CreateEngagement($input: EngagementCreateInput!) {
  engagement_create(input: $input) {
    uuid
  }
}

mutation CreateAssociation($input: AssociationCreateInput!) {
  association_create(input: $input) {
    uuid
  }
}

mutation CreateITSystem($input: ITSystemCreateInput!) {
  itsystem_create(input: $input) {
    uuid
  }
}

mutation CreateITUser($input: ITUserCreateInput!) {
  ituser_create(input: $input) {
    uuid
  }
}

mutation UpdateOrgUnit($input: OrganisationUnitUpdateInput!) {
  org_unit_update(input: $input) {
    uuid
  }
}
