# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import uuid
from collections.abc import AsyncIterator
from datetime import datetime
from typing import Any
from uuid import UUID
from zoneinfo import ZoneInfo

import pytest
from fastapi.applications import FastAPI
from httpx import AsyncClient

from orggatekeeper.autogenerated_graphql_client import ClassCreateInput
from orggatekeeper.autogenerated_graphql_client import CreateClassClassCreate
from orggatekeeper.autogenerated_graphql_client import CreateEmployeeEmployeeCreate
from orggatekeeper.autogenerated_graphql_client import CreateFacetFacetCreate
from orggatekeeper.autogenerated_graphql_client import CreateITSystemItsystemCreate
from orggatekeeper.autogenerated_graphql_client import CreateOrgUnitOrgUnitCreate
from orggatekeeper.autogenerated_graphql_client import EmployeeCreateInput
from orggatekeeper.autogenerated_graphql_client import FacetCreateInput
from orggatekeeper.autogenerated_graphql_client import GraphQLClient
from orggatekeeper.autogenerated_graphql_client import ITSystemCreateInput
from orggatekeeper.autogenerated_graphql_client import OrganisationUnitCreateInput
from orggatekeeper.autogenerated_graphql_client import RAOpenValidityInput
from orggatekeeper.autogenerated_graphql_client import RAValidityInput
from orggatekeeper.autogenerated_graphql_client import ValidityInput
from orggatekeeper.main import create_app


class _NoopAMQPSystem:
    """Stand-in for MOAMQPSystem that does not consume any messages."""

    async def __aenter__(self) -> "_NoopAMQPSystem":
        return self

    async def __aexit__(self, *args: Any) -> None:
        return None


@pytest.fixture
def disable_amqp() -> None:
    """Explicitly request that the AMQP event system be disabled for a test."""


@pytest.fixture
async def app(
    request: pytest.FixtureRequest, monkeypatch: pytest.MonkeyPatch
) -> FastAPI:
    if "disable_amqp" in request.fixturenames:
        monkeypatch.setattr(
            "orggatekeeper.main.MOAMQPSystem",
            lambda *args, **kwargs: _NoopAMQPSystem(),
        )
    return create_app()


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v22", http_client=mo_client
    )
    async with graphql_client as client:
        yield client


# autouse because the integration does not function if these are not pre-defined
@pytest.fixture(autouse=True)
async def org_unit_hierarchy_classes(
    graphql_client: GraphQLClient,
    org_unit_hierarchy_facet: CreateFacetFacetCreate,
) -> dict[str, UUID]:
    """
    Creates all the "org unit hierarchy" classes that this integration expects
    """

    user_keys = [
        "linjeorg",
        "selvejet",
        "hide",
        "NA",
    ]

    classes: dict[str, UUID] = {}
    for user_key in user_keys:
        res = await graphql_client.create_class(
            ClassCreateInput(
                name=user_key,
                user_key=user_key,
                facet_uuid=org_unit_hierarchy_facet.uuid,
                validity=ValidityInput(),
            )
        )
        classes[user_key] = res.uuid

    return classes


@pytest.fixture
async def default_org_unit(
    graphql_client: GraphQLClient,
) -> CreateOrgUnitOrgUnitCreate:
    tz = ZoneInfo("Europe/Copenhagen")
    long_time_ago = datetime(1970, 1, 1, tzinfo=tz)

    return await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            uuid=None,
            validity=RAValidityInput(**{"from": long_time_ago}),
            name="E Corp",
            org_unit_type=uuid.uuid4(),
            user_key=None,
            parent=None,
            time_planning=None,
            org_unit_level=None,
            org_unit_hierarchy=None,
        )
    )


@pytest.fixture
async def default_employee(
    graphql_client: GraphQLClient,
) -> CreateEmployeeEmployeeCreate:
    return await graphql_client.create_employee(
        EmployeeCreateInput(
            given_name="Gneurshk",
            surname="Gronk",
        )
    )


@pytest.fixture
async def engagement_type_facet(
    graphql_client: GraphQLClient,
) -> CreateFacetFacetCreate:
    return await graphql_client.create_facet(
        FacetCreateInput(user_key="engagement_type", validity=ValidityInput())
    )


@pytest.fixture
async def default_engagement_type(
    graphql_client: GraphQLClient,
    engagement_type_facet: CreateFacetFacetCreate,
) -> CreateClassClassCreate:
    return await graphql_client.create_class(
        ClassCreateInput(
            name="Månedslønnet, fuldtid",
            user_key="fuldtid",
            facet_uuid=engagement_type_facet.uuid,
            validity=ValidityInput(),
        )
    )


@pytest.fixture
async def association_type_facet(
    graphql_client: GraphQLClient,
) -> CreateFacetFacetCreate:
    return await graphql_client.create_facet(
        FacetCreateInput(user_key="association_type", validity=ValidityInput())
    )


@pytest.fixture
async def default_association_type(
    graphql_client: GraphQLClient,
    association_type_facet: CreateFacetFacetCreate,
) -> CreateClassClassCreate:
    return await graphql_client.create_class(
        ClassCreateInput(
            name="Member",
            user_key="Member",
            facet_uuid=association_type_facet.uuid,
            validity=ValidityInput(),
        )
    )


@pytest.fixture
async def default_it_system(
    graphql_client: GraphQLClient,
) -> CreateITSystemItsystemCreate:
    return await graphql_client.create_i_t_system(
        ITSystemCreateInput(
            user_key="SD_uuid",
            name="SD UUID",
            validity=RAOpenValidityInput(),
        )
    )


@pytest.fixture
async def org_unit_hierarchy_facet(
    graphql_client: GraphQLClient,
) -> CreateFacetFacetCreate:
    return await graphql_client.create_facet(
        FacetCreateInput(user_key="org_unit_hierarchy", validity=ValidityInput())
    )


@pytest.fixture
async def org_unit_level_facet(graphql_client: GraphQLClient) -> CreateFacetFacetCreate:
    return await graphql_client.create_facet(
        FacetCreateInput(user_key="org_unit_level", validity=ValidityInput())
    )


@pytest.fixture
async def org_unit_level_classes(
    graphql_client: GraphQLClient,
    org_unit_level_facet: CreateFacetFacetCreate,
) -> dict[str, UUID]:
    """
    Creates all the "org unit hierarchy" classes that this integration expects
    """

    user_keys = [
        "NY1-niveau",
        "NY2-niveau",
    ]

    classes: dict[str, UUID] = {}
    for user_key in user_keys:
        res = await graphql_client.create_class(
            ClassCreateInput(
                name=user_key,
                user_key=user_key,
                facet_uuid=org_unit_level_facet.uuid,
                validity=ValidityInput(),
            )
        )
        classes[user_key] = res.uuid

    return classes
