# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import datetime
from datetime import timedelta
from uuid import UUID
from zoneinfo import ZoneInfo

import pytest
from more_itertools import one
from ramodels.mo import OrganisationUnit
from ramodels.mo import Validity
from ramodels.mo._shared import OrgUnitHierarchy
from ramodels.mo._shared import OrgUnitType
from ramodels.mo._shared import ParentRef

from orggatekeeper import model_client_shim
from orggatekeeper.autogenerated_graphql_client import CreateOrgUnitOrgUnitCreate
from orggatekeeper.autogenerated_graphql_client import GraphQLClient
from orggatekeeper.autogenerated_graphql_client import OrganisationUnitCreateInput
from orggatekeeper.autogenerated_graphql_client import OrganisationUnitFilter
from orggatekeeper.autogenerated_graphql_client import RAValidityInput
from orggatekeeper.autogenerated_graphql_client.create_class import (
    CreateClassClassCreate,
)


@pytest.mark.integration_test
async def test_edit_org_unit(
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    default_org_unit_type: CreateClassClassCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
) -> None:
    """
    Tests whether `model_client_shim.edit` works as expected, by performing
    an edit that is similar to the ones the integration makes.
    """

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)
    t1 = datetime(year=2021, month=1, day=1, tzinfo=tz)
    t2 = datetime(year=2022, month=1, day=1, tzinfo=tz)

    # Arrange
    org_unit_name = "Allsafe Cybersecurity"
    org_unit_type = default_org_unit_type.uuid
    org_unit = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            user_key=org_unit_name,
            name=org_unit_name,
            parent=default_org_unit.uuid,
            org_unit_type=org_unit_type,
        )
    )

    new_parent = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Parent Org Unit",
            org_unit_type=default_org_unit_type.uuid,
        )
    )

    # Act

    # edit the org unit in the interval [t1, t2] to have hierarchy "NA" and
    # parent `new_parent`
    org_unit_edit = OrganisationUnit(
        uuid=org_unit.uuid,
        type_="org_unit",
        user_key=org_unit_name,
        name=org_unit_name,
        validity=Validity(**{"from": t1, "to": t2}),
        parent=ParentRef(uuid=new_parent.uuid),
        org_unit_hierarchy=OrgUnitHierarchy(uuid=org_unit_hierarchy_classes["NA"]),
        org_unit_type=OrgUnitType(uuid=org_unit_type),
        org_unit_level=None,
        details=None,
    )
    res_uuid = one(await model_client_shim.edit(graphql_client, org_unit_edit))

    # Assert

    assert res_uuid == str(org_unit.uuid)

    org_unit_after = await graphql_client.get_org_unit_details(
        OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
    )
    org_unit_after_obj = one(org_unit_after.objects)
    v1, v2, v3 = org_unit_after_obj.validities

    # before t1, unchanged
    assert v1.unit_hierarchy_response is None
    assert v1.parent_response is not None
    assert v1.parent_response.uuid == default_org_unit.uuid
    assert v1.validity.from_ == t0
    assert v1.validity.to == t1 - timedelta(days=1)

    # in range [t1, t2] we expect the hierarchy and parent to be set
    assert v2.unit_hierarchy_response is not None
    assert v2.unit_hierarchy_response.uuid == org_unit_hierarchy_classes["NA"]
    assert v2.parent_response is not None
    assert v2.parent_response.uuid == new_parent.uuid
    assert v2.validity.from_ == t1
    assert v2.validity.to == t2

    # after t2, unchanged
    assert v3.unit_hierarchy_response is None
    assert v3.parent_response is not None
    assert v3.parent_response.uuid == default_org_unit.uuid
    assert v3.validity.from_ == t2 + timedelta(days=1)
    assert v3.validity.to is None


@pytest.mark.integration_test
async def test_edit_org_unit_preserves_none_fields(
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    default_org_unit_type: CreateClassClassCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
    org_unit_level_classes: dict[str, UUID],
) -> None:
    """
    Editing an org unit with a payload where a bunch of fields are set to
    `None` must leave those fields unchanged.
    """

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)
    t1 = datetime(year=2021, month=1, day=1, tzinfo=tz)

    # Arrange

    org_unit_name = "FooBar ApS"
    hierarchy_uuid = org_unit_hierarchy_classes["linjeorg"]
    level_uuid = org_unit_level_classes["NY1-niveau"]

    # Create the org unit with all its optional fields populated.
    org_unit = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            user_key=org_unit_name,
            name=org_unit_name,
            parent=default_org_unit.uuid,
            org_unit_type=default_org_unit_type.uuid,
            org_unit_hierarchy=hierarchy_uuid,
            org_unit_level=level_uuid,
        )
    )

    # Act

    # Edit the org unit in the interval [t1, ...), changing only the name.
    # Every optional field is set to `None`.
    new_name = "FooBar Group A/S"
    org_unit_edit = OrganisationUnit(
        uuid=org_unit.uuid,
        type_="org_unit",
        user_key=org_unit_name,
        name=new_name,
        validity=Validity(**{"from": t1}),
        org_unit_type=OrgUnitType(uuid=default_org_unit_type.uuid),
        parent=None,
        org_unit_hierarchy=None,
        org_unit_level=None,
        details=None,
    )
    res_uuid = one(await model_client_shim.edit(graphql_client, org_unit_edit))

    # Assert

    assert res_uuid == str(org_unit.uuid)

    org_unit_after = await graphql_client.get_org_unit_details(
        OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
    )
    org_unit_after_obj = one(org_unit_after.objects)
    v1, v2 = org_unit_after_obj.validities

    # Before the edit: the original values, over [t0, t1).
    assert v1.name == org_unit_name
    assert v1.validity.from_ == t0
    assert v1.validity.to == t1 - timedelta(days=1)

    # After the edit: the name changed (proving the edit was performed) ...
    assert v2.name == new_name
    assert v2.validity.from_ == t1
    assert v2.validity.to is None

    # ... while every field passed as `None` remains unchanged.
    assert v2.user_key == org_unit_name
    assert v2.parent_response is not None
    assert v2.parent_response.uuid == default_org_unit.uuid
    assert v2.unit_hierarchy_response is not None
    assert v2.unit_hierarchy_response.uuid == hierarchy_uuid
    assert v2.unit_level_response is not None
    assert v2.unit_level_response.uuid == level_uuid
    assert v2.unit_type_response is not None
    assert v2.unit_type_response.uuid == default_org_unit_type.uuid
