# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""
Tests the integration through its web API endpoints, without involving the AMQP
event system.

These tests are intended to catch any breakage in the shape or semantics of the
public APIs, they do not cover the entirety of the integration logic.
"""

from datetime import datetime
from uuid import UUID
from uuid import uuid4
from zoneinfo import ZoneInfo

import pytest
import structlog
from httpx import AsyncClient
from more_itertools import one

from orggatekeeper.autogenerated_graphql_client import CreateClassClassCreate
from orggatekeeper.autogenerated_graphql_client import CreateEmployeeEmployeeCreate
from orggatekeeper.autogenerated_graphql_client import CreateOrgUnitOrgUnitCreate
from orggatekeeper.autogenerated_graphql_client import EngagementCreateInput
from orggatekeeper.autogenerated_graphql_client import GraphQLClient
from orggatekeeper.autogenerated_graphql_client import OrganisationUnitCreateInput
from orggatekeeper.autogenerated_graphql_client import OrganisationUnitFilter
from orggatekeeper.autogenerated_graphql_client import RAValidityInput

logger = structlog.stdlib.get_logger()


@pytest.mark.integration_test
async def test_index(
    test_client: AsyncClient,
) -> None:
    res = await test_client.get("/")
    assert res.json() == {"name": "orggatekeeper"}


@pytest.mark.integration_test
async def test_metrics(test_client: AsyncClient) -> None:
    res = await test_client.get("/metrics")
    assert "# TYPE build_information_info gauge" in res.raise_for_status().text


@pytest.mark.integration_test
async def test_liveness(test_client: AsyncClient) -> None:
    res = await test_client.get("/health/live")
    assert res.status_code == 204
    assert res.text == ""


@pytest.mark.integration_test
async def test_readiness(test_client: AsyncClient) -> None:
    res = await test_client.get("/health/ready")
    assert res.status_code == 204
    assert res.text == ""


@pytest.mark.usefixtures("disable_amqp")
@pytest.mark.integration_test
async def test_trigger_uuid_na(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
) -> None:
    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)

    # Arrange
    org_unit = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Allsafe Cybersecurity",
            parent=default_org_unit.uuid,
            org_unit_type=uuid4(),
        )
    )

    # Act
    response = await test_client.post(f"/trigger/{org_unit.uuid}")
    assert response.raise_for_status().json() == {"status": "OK"}

    # Assert
    hierarchy_after = await graphql_client.get_org_unit_hierarchy(
        OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
    )
    hierarchy_after_obj = one(hierarchy_after.objects)
    v1, v2 = hierarchy_after_obj.validities
    assert v1.unit_hierarchy_response is None
    assert v2.unit_hierarchy_response is not None
    hierarchy = one(v2.unit_hierarchy_response.validities)
    assert hierarchy.uuid == org_unit_hierarchy_classes["NA"]


_HIDE_ORG_UNIT_UUID = uuid4()


@pytest.mark.usefixtures("disable_amqp")
@pytest.mark.integration_test
@pytest.mark.envvar({"HIDDEN": f'["{_HIDE_ORG_UNIT_UUID}"]'})
async def test_trigger_uuid_hide(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
) -> None:
    """An org unit listed in settings.hidden should be marked as 'hide'."""

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)

    # Arrange
    org_unit = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Hidden Org Unit",
            parent=default_org_unit.uuid,
            org_unit_type=uuid4(),
            uuid=_HIDE_ORG_UNIT_UUID,
        )
    )

    # Act
    response = await test_client.post(f"/trigger/{org_unit.uuid}")
    assert response.raise_for_status().json() == {"status": "OK"}

    # Assert
    hierarchy_after = await graphql_client.get_org_unit_hierarchy(
        OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
    )
    hierarchy_after_obj = one(hierarchy_after.objects)
    v1, v2 = hierarchy_after_obj.validities
    assert v1.unit_hierarchy_response is None
    assert v2.unit_hierarchy_response is not None
    hierarchy = one(v2.unit_hierarchy_response.validities)
    assert hierarchy.uuid == org_unit_hierarchy_classes["hide"]


_SELF_OWNED_ROOT_UUID = uuid4()


@pytest.mark.usefixtures("disable_amqp")
@pytest.mark.integration_test
@pytest.mark.envvar({"SELF_OWNED_ROOT_UNITS": f'["{_SELF_OWNED_ROOT_UUID}"]'})
async def test_trigger_uuid_selvejet(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
) -> None:
    """An org unit that is a descendant of a self-owned root should be 'selvejet'."""

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)

    # Arrange
    self_owned_root = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Self-owned Root",
            parent=default_org_unit.uuid,
            org_unit_type=uuid4(),
            uuid=_SELF_OWNED_ROOT_UUID,
        )
    )

    child = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Self-owned Child",
            parent=self_owned_root.uuid,
            org_unit_type=uuid4(),
        )
    )

    # Act
    response = await test_client.post(f"/trigger/{child.uuid}")
    assert response.raise_for_status().json() == {"status": "OK"}

    # Assert
    hierarchy_after = await graphql_client.get_org_unit_hierarchy(
        OrganisationUnitFilter(from_date=None, to_date=None, uuids=[child.uuid])
    )
    hierarchy_after_obj = one(hierarchy_after.objects)
    v1, v2 = hierarchy_after_obj.validities
    assert v1.unit_hierarchy_response is None
    assert v2.unit_hierarchy_response is not None
    hierarchy = one(v2.unit_hierarchy_response.validities)
    assert hierarchy.uuid == org_unit_hierarchy_classes["selvejet"]


_LINE_MANAGEMENT_ROOT_UUID = uuid4()


@pytest.mark.usefixtures("disable_amqp")
@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LINE_MANAGEMENT_TOP_LEVEL_UUIDS": f'["{_LINE_MANAGEMENT_ROOT_UUID}"]',
    }
)
async def test_trigger_uuid_linjeorg(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    default_employee: CreateEmployeeEmployeeCreate,
    default_engagement_type: CreateClassClassCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
    org_unit_level_classes: dict[str, UUID],
) -> None:
    """A unit below a line-management root with an NY-niveau level is 'linjeorg'."""

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)

    # Arrange
    line_management_root = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Line Management Root",
            parent=default_org_unit.uuid,
            org_unit_type=uuid4(),
            uuid=_LINE_MANAGEMENT_ROOT_UUID,
        )
    )

    child = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Line Management Child",
            parent=line_management_root.uuid,
            org_unit_type=uuid4(),
            org_unit_level=org_unit_level_classes["NY1-niveau"],
        )
    )

    _ = await graphql_client.create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            org_unit=child.uuid,
            employee=default_employee.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid4(),
        )
    )

    # Act
    response = await test_client.post(f"/trigger/{child.uuid}")
    assert response.raise_for_status().json() == {"status": "OK"}

    # Assert
    hierarchy_after = await graphql_client.get_org_unit_hierarchy(
        OrganisationUnitFilter(from_date=None, to_date=None, uuids=[child.uuid])
    )
    hierarchy_after_obj = one(hierarchy_after.objects)
    v1, v2 = hierarchy_after_obj.validities
    assert v1.unit_hierarchy_response is None
    assert v2.unit_hierarchy_response is not None
    hierarchy = one(v2.unit_hierarchy_response.validities)
    assert hierarchy.uuid == org_unit_hierarchy_classes["linjeorg"]


@pytest.mark.usefixtures("disable_amqp")
@pytest.mark.integration_test
async def test_trigger_all(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
) -> None:
    """POST /trigger/all updates org_unit_hierarchy on every org unit.

    Unlike /trigger/{uuid}, the endpoint returns 202 with no body, and
    processes every org unit in MO rather than a single one.
    """

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)

    # Arrange
    org_unit_1 = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Org Unit 1",
            parent=default_org_unit.uuid,
            org_unit_type=uuid4(),
        )
    )

    org_unit_2 = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Org Unit 2",
            parent=default_org_unit.uuid,
            org_unit_type=uuid4(),
        )
    )

    # Act
    response = await test_client.post("/trigger/all")
    assert response.status_code == 202

    # Assert
    for org_unit in (org_unit_1, org_unit_2):
        hierarchy_after = await graphql_client.get_org_unit_hierarchy(
            OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
        )
        hierarchy_after_obj = one(hierarchy_after.objects)
        v1, v2 = hierarchy_after_obj.validities
        assert v1.unit_hierarchy_response is None
        assert v2.unit_hierarchy_response is not None
        hierarchy = one(v2.unit_hierarchy_response.validities)
        assert hierarchy.uuid == org_unit_hierarchy_classes["NA"]


@pytest.mark.usefixtures("disable_amqp")
@pytest.mark.integration_test
async def test_ensure_no_unset_ok(test_client: AsyncClient) -> None:
    res = await test_client.post("/ensure-no-unset")
    assert res.raise_for_status().json() == {"status": "OK"}


@pytest.mark.usefixtures("disable_amqp", "default_org_unit")
@pytest.mark.integration_test
async def test_ensure_no_unset_updated(test_client: AsyncClient) -> None:
    res = await test_client.post("/ensure-no-unset")
    assert res.raise_for_status().json() == {"status": "Updated 1 orgunits"}
