# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import datetime
from datetime import timedelta
from uuid import UUID
from uuid import uuid4
from zoneinfo import ZoneInfo

import pytest
from fastramqpi.raclients.modelclient.mo import ModelClient
from more_itertools import one
from ramodels.mo import OrganisationUnit
from ramodels.mo import Validity
from ramodels.mo._shared import OrgUnitHierarchy
from ramodels.mo._shared import OrgUnitType
from ramodels.mo._shared import ParentRef

from orggatekeeper import model_client_shim
from orggatekeeper.autogenerated_graphql_client import CreateOrgUnitOrgUnitCreate
from orggatekeeper.autogenerated_graphql_client import GraphQLClient
from orggatekeeper.autogenerated_graphql_client import OrganisationUnitCreateInput
from orggatekeeper.autogenerated_graphql_client import OrganisationUnitFilter
from orggatekeeper.autogenerated_graphql_client import RAValidityInput


@pytest.mark.integration_test
async def test_edit_org_unit(
    legacy_model_client: ModelClient,
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
) -> None:
    """
    Tests whether `model_client_shim.edit` works as expected, by performing
    an edit that is similar to the ones the integration makes.
    """

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)
    t1 = datetime(year=2021, month=1, day=1, tzinfo=tz)

    # Arrange
    org_unit_name = "Allsafe Cybersecurity"
    org_unit_type = uuid4()
    org_unit = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            user_key=org_unit_name,
            name=org_unit_name,
            parent=default_org_unit.uuid,
            org_unit_type=org_unit_type,
        )
    )

    new_parent = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Parent Org Unit",
            org_unit_type=uuid4(),
        )
    )

    # Act

    # edit the org unit in the interval [t1, ...) to have hierarchy "NA" and
    # parent `new_parent`
    org_unit_edit = OrganisationUnit(
        uuid=org_unit.uuid,
        type_="org_unit",
        user_key=org_unit_name,
        name=org_unit_name,
        validity=Validity(**{"from": t1}),
        parent=ParentRef(uuid=new_parent.uuid),
        org_unit_hierarchy=OrgUnitHierarchy(uuid=org_unit_hierarchy_classes["NA"]),
        org_unit_type=OrgUnitType(uuid=org_unit_type),
        org_unit_level=None,
        details=None,
    )
    res_uuid = one(await model_client_shim.edit(legacy_model_client, org_unit_edit))

    # Assert

    assert res_uuid == str(org_unit.uuid)

    org_unit_after = await graphql_client.get_org_unit_hierarchy_and_parent(
        OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
    )
    org_unit_after_obj = one(org_unit_after.objects)
    v1, v2 = org_unit_after_obj.validities

    assert v1.unit_hierarchy_response is None
    assert v1.parent_response is not None
    assert v1.parent_response.uuid == default_org_unit.uuid
    assert v1.validity.from_ == t0
    assert v1.validity.to == t1 - timedelta(days=1)

    assert v2.unit_hierarchy_response is not None
    assert v2.unit_hierarchy_response.uuid == org_unit_hierarchy_classes["NA"]
    assert v2.parent_response is not None
    assert v2.parent_response.uuid == new_parent.uuid
    assert v2.validity.from_ == t1
    assert v2.validity.to is None
