# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""
Tests the integration through its AMQP event system.

These tests check that the different types of events trigger the integration
as espected. They do not check the entirety of the integration's logic.
"""

from datetime import datetime
from unittest.mock import AsyncMock
from uuid import UUID
from uuid import uuid4
from zoneinfo import ZoneInfo

import pytest
from fastramqpi.pytest_util import retry
from fastramqpi.pytest_util import stop_after_delay
from more_itertools import one
from pytest import MonkeyPatch

from orggatekeeper import calculate
from orggatekeeper.autogenerated_graphql_client import AssociationCreateInput
from orggatekeeper.autogenerated_graphql_client import CreateClassClassCreate
from orggatekeeper.autogenerated_graphql_client import CreateEmployeeEmployeeCreate
from orggatekeeper.autogenerated_graphql_client import CreateITSystemItsystemCreate
from orggatekeeper.autogenerated_graphql_client import CreateOrgUnitOrgUnitCreate
from orggatekeeper.autogenerated_graphql_client import EngagementCreateInput
from orggatekeeper.autogenerated_graphql_client import GraphQLClient
from orggatekeeper.autogenerated_graphql_client import ITUserCreateInput
from orggatekeeper.autogenerated_graphql_client import OrganisationUnitCreateInput
from orggatekeeper.autogenerated_graphql_client import OrganisationUnitFilter
from orggatekeeper.autogenerated_graphql_client import RAValidityInput


@pytest.mark.usefixtures("test_client")
@pytest.mark.integration_test
async def test_org_unit_event(
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
) -> None:
    """Creating an org unit emits an `org_unit` event, which should cause the
    org unit to be updated to the `NA` hierarchy class.
    """

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)

    org_unit = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Engagement Org",
            parent=default_org_unit.uuid,
            org_unit_type=uuid4(),
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        hierarchy_after = await graphql_client.get_org_unit_hierarchy(
            OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
        )
        hierarchy_after_obj = one(hierarchy_after.objects)
        v1, v2 = hierarchy_after_obj.validities
        assert v1.unit_hierarchy_response is None
        assert v2.unit_hierarchy_response is not None
        hierarchy = one(v2.unit_hierarchy_response.validities)
        assert hierarchy.uuid == org_unit_hierarchy_classes["NA"]

    await verify()


@pytest.mark.usefixtures("test_client")
@pytest.mark.integration_test
async def test_engagement_event(
    monkeypatch: MonkeyPatch,
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    default_employee: CreateEmployeeEmployeeCreate,
    default_engagement_type: CreateClassClassCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
) -> None:
    """
    Creating an engagement emits an `engagement` event. This should cause
    the org unit the association is attached to to be updated.
    """

    # disable events on org unit changes, so we only test engagement events
    monkeypatch.setattr(calculate, "org_unit_handler", AsyncMock())

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)

    org_unit = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Engagement Org",
            parent=default_org_unit.uuid,
            org_unit_type=uuid4(),
        )
    )

    # assert that a new org unit has no hierarchy
    hierarchy_before = await graphql_client.get_org_unit_hierarchy(
        OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
    )
    hierarchy_before_obj = one(hierarchy_before.objects)
    hierarchy_before_validity = one(hierarchy_before_obj.validities)
    assert hierarchy_before_validity.unit_hierarchy_response is None

    _ = await graphql_client.create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            org_unit=org_unit.uuid,
            employee=default_employee.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid4(),
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        hierarchy_after = await graphql_client.get_org_unit_hierarchy(
            OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
        )
        hierarchy_after_obj = one(hierarchy_after.objects)
        v1, v2 = hierarchy_after_obj.validities
        assert v1.unit_hierarchy_response is None
        assert v2.unit_hierarchy_response is not None
        hierarchy = one(v2.unit_hierarchy_response.validities)
        assert hierarchy.uuid == org_unit_hierarchy_classes["NA"]

    await verify()


@pytest.mark.usefixtures("test_client")
@pytest.mark.integration_test
async def test_association_event(
    monkeypatch: MonkeyPatch,
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    default_employee: CreateEmployeeEmployeeCreate,
    default_association_type: CreateClassClassCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
) -> None:
    """Creating an association emits an `association` event. This should cause
    the org unit the association is attached to to be updated.
    """

    # disable events on org unit changes, so we only test association events
    monkeypatch.setattr(calculate, "org_unit_handler", AsyncMock())

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)

    org_unit = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="Association Org",
            parent=default_org_unit.uuid,
            org_unit_type=uuid4(),
        )
    )

    # assert that a new org unit has no hierarchy
    hierarchy_before = await graphql_client.get_org_unit_hierarchy(
        OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
    )
    hierarchy_before_obj = one(hierarchy_before.objects)
    hierarchy_before_validity = one(hierarchy_before_obj.validities)
    assert hierarchy_before_validity.unit_hierarchy_response is None

    _ = await graphql_client.create_association(
        AssociationCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            org_unit=org_unit.uuid,
            person=default_employee.uuid,
            association_type=default_association_type.uuid,
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        hierarchy_after = await graphql_client.get_org_unit_hierarchy(
            OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
        )
        hierarchy_after_obj = one(hierarchy_after.objects)
        v1, v2 = hierarchy_after_obj.validities
        assert v1.unit_hierarchy_response is None
        assert v2.unit_hierarchy_response is not None
        hierarchy = one(v2.unit_hierarchy_response.validities)
        assert hierarchy.uuid == org_unit_hierarchy_classes["NA"]

    await verify()


@pytest.mark.usefixtures("test_client")
@pytest.mark.integration_test
async def test_ituser_event(
    monkeypatch: MonkeyPatch,
    graphql_client: GraphQLClient,
    default_org_unit: CreateOrgUnitOrgUnitCreate,
    default_it_system: CreateITSystemItsystemCreate,
    org_unit_hierarchy_classes: dict[str, UUID],
) -> None:
    """
    Creating an ituser attached to an org unit emits an `ituser` event. This
    should cause the org unit the association is attached to to be updated.
    """

    # disable events on org unit changes, so we only test ituser events
    monkeypatch.setattr(calculate, "org_unit_handler", AsyncMock())

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(year=2020, month=1, day=1, tzinfo=tz)

    org_unit = await graphql_client.create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            name="ITUser Org",
            parent=default_org_unit.uuid,
            org_unit_type=uuid4(),
        )
    )

    # assert that a new org unit has no hierarchy
    hierarchy_before = await graphql_client.get_org_unit_hierarchy(
        OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
    )
    hierarchy_before_obj = one(hierarchy_before.objects)
    hierarchy_before_validity = one(hierarchy_before_obj.validities)
    assert hierarchy_before_validity.unit_hierarchy_response is None

    _ = await graphql_client.create_i_t_user(
        ITUserCreateInput(
            validity=RAValidityInput(**{"from": t0}),
            org_unit=org_unit.uuid,
            itsystem=default_it_system.uuid,
            user_key="account1",
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        hierarchy_after = await graphql_client.get_org_unit_hierarchy(
            OrganisationUnitFilter(from_date=None, to_date=None, uuids=[org_unit.uuid])
        )
        hierarchy_after_obj = one(hierarchy_after.objects)
        v1, v2 = hierarchy_after_obj.validities
        assert v1.unit_hierarchy_response is None
        assert v2.unit_hierarchy_response is not None
        hierarchy = one(v2.unit_hierarchy_response.validities)
        assert hierarchy.uuid == org_unit_hierarchy_classes["NA"]

    await verify()
