# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""Shims for adapting calls to ModelClient to call the graphql API instead."""

from typing import Any

from ramodels.mo import OrganisationUnit

from .autogenerated_graphql_client import GraphQLClient
from .autogenerated_graphql_client import OrganisationUnitUpdateInput
from .autogenerated_graphql_client import RAValidityInput


async def edit(gql_client: GraphQLClient, org_unit: OrganisationUnit) -> list[str]:
    # the dictionary unpacking is needed because `from` is not a valid python
    # identifier, and ariadne defines the type to have a field called `from`
    validity = RAValidityInput(
        **{"from": org_unit.validity.from_date, "to": org_unit.validity.to_date}
    )

    # We first have to filter out any `None` fields in the payload. In ModelClient,
    # a `None` field leaves the object unchanged, whereas in GraphQL a `None` field
    # would "unset" the field in the object.
    optional_fields: dict[str, Any] = {}
    if org_unit.parent:
        optional_fields["parent"] = org_unit.parent.uuid
    if org_unit.org_unit_hierarchy:
        optional_fields["org_unit_hierarchy"] = org_unit.org_unit_hierarchy.uuid
    if org_unit.org_unit_type:
        optional_fields["org_unit_type"] = org_unit.org_unit_type.uuid
    if org_unit.org_unit_level:
        optional_fields["org_unit_level"] = org_unit.org_unit_level.uuid

    response = await gql_client.update_org_unit(
        OrganisationUnitUpdateInput(
            uuid=org_unit.uuid,
            validity=validity,
            user_key=org_unit.user_key,
            name=org_unit.name,
            **optional_fields,
        )
    )
    return [str(response.uuid)]
