# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""Shims for adapting calls to ModelClient to call the graphql API instead."""

from ramodels.mo import OrganisationUnit

from .autogenerated_graphql_client import GraphQLClient
from .autogenerated_graphql_client import OrganisationUnitUpdateInput
from .autogenerated_graphql_client import RAValidityInput


async def edit(gql_client: GraphQLClient, edit_obj: OrganisationUnit) -> list[str]:
    # the dictionary unpacking is needed because `from` is not a valid python
    # identifier, and ariadne defines the type to have a field called `from`
    validity = RAValidityInput(
        **{"from": edit_obj.validity.from_date, "to": edit_obj.validity.to_date}
    )

    parent = edit_obj.parent.uuid if edit_obj.parent else None
    org_unit_hierarchy = (
        edit_obj.org_unit_hierarchy.uuid if edit_obj.org_unit_hierarchy else None
    )
    org_unit_type = edit_obj.org_unit_type.uuid if edit_obj.org_unit_type else None
    org_unit_level = edit_obj.org_unit_level.uuid if edit_obj.org_unit_level else None

    response = await gql_client.update_org_unit(
        OrganisationUnitUpdateInput(
            uuid=edit_obj.uuid,
            validity=validity,
            user_key=edit_obj.user_key,
            name=edit_obj.name,
            parent=parent,
            org_unit_hierarchy=org_unit_hierarchy,
            org_unit_type=org_unit_type,
            org_unit_level=org_unit_level,
        )
    )
    return [str(response.uuid)]
